src/ClearSkyLettings/Models/Enquiry.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.ComponentModel;

namespace ClearSkyLettings.Models
{
    public class Enquiry
    {
        public long Id { get; set; }

        [DisplayName("Date Enquired")]
        public DateTime DateEnquired { get; set; }

        public long PropertyId { get; set; }
        public Property Property { get; set; }

        public string UserId { get; set; }
        public IdentityUser User { get; set; }
    }
}

src/ClearSkyLettings/Models/ErrorViewModel.cs
namespace ClearSkyLettings.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/ClearSkyLettings/Models/MakeEnquiryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ClearSkyLettings.Models
{
    public class MakeEnquiryViewModel
    {
        [Required]
        public long PropertyId { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
    }
}

src/ClearSkyLettings/Models/Property.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ClearSkyLettings.Models
{
    public class Property
    {
        public long Id { get; set; }

        public string Address { get; set; }

        [DisplayName("Monthly Price")]
        public decimal MonthlyPrice { get; set; }

        public decimal Deposit { get; set; }

        [DisplayName("Date Added")]
        [DataType(DataType.Date)]
        public DateTime DateAdded { get; set; }

        [DisplayName("Furnished?")]
        public bool IsFurnished { get; set; }

        [DisplayName("No. Bedrooms")]
        public int NumberBedrooms { get; set; }

        [DisplayName("No. Bathrooms")]
        public int NumberBathrooms { get; set; }

        public string Description { get; set; }

        [DisplayName("Property Type")]
        public long PropertyTypeId { get; set; }
        public PropertyType PropertyType { get; set; }
    }
}

src/ClearSkyLettings/Models/PropertyType.cs
using System.Collections.Generic;
using System.ComponentModel;

namespace ClearSkyLettings.Models
{
    public class PropertyType
    {
        public long Id { get; set; }

        [DisplayName("Property Type")]
        public string Name { get; set; }

        public IEnumerable<Property> Properties { get; set; }
    }
}

src/ClearSkyLettings/Controllers/EnquiriesController.cs
using ClearSkyLettings.Domain.Enquiries.Commands;
using ClearSkyLettings.Domain.Enquiries.Queries;
using ClearSkyLettings.Models;
using ClearSkyLettings.Util.Extensions.Alerts;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ClearSkyLettings.Controllers
{
    public class EnquiriesController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IMediator _mediator;

        public EnquiriesController(UserManager<IdentityUser> userManager, IMediator mediator)
        {
            _userManager = userManager;
            _mediator = mediator;
        }

        // GET: Enquiries
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var enquiries = await _mediator.Send(new GetAllUserEnquiriesQuery(userId));
            return View(enquiries);
        }

        // GET: Enquiries/Make/5
        public async Task<IActionResult> Make(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // If logged in, make the enquiry immediately
            if (User.Identity.IsAuthenticated)
            {
                var userId = _userManager.GetUserId(User);
                var success = await _mediator.Send(new MakeEnquiryAsUserCommand(id.Value, userId));
                var actionResult = RedirectToAction(nameof(Index));

                if (success)
                {
                    return actionResult.WithSuccess("Success", "The enquiry was successfully made.");
                }

                return actionResult.WithDanger("Error", "You have already made an enquiry for that property.");
            }

            // If not logged in, show view for user to type in email
            return View(new MakeEnquiryViewModel
            {
                PropertyId = id.Value
            });
        }

        // POST: Enquiries/Make
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Make(MakeEnquiryViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var success = await _mediator.Send(new MakeEnquiryAsGuestCommand(viewModel.PropertyId, viewModel.Email));
                if (success)
                {
                    return RedirectToAction("Details", "Properties", new { id = viewModel.PropertyId })
                        .WithSuccess("Success", "The enquiry was successfully made.");
                }

                return RedirectToAction("Index", "Properties", new { })
                    .WithDanger("Error", "It was not possible to create the enquiry.");
            }

            return View(viewModel);
        }

        // GET: Enquiries/Details/5
        [Authorize]
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userId = _userManager.GetUserId(User);
            var enquiry = await _mediator.Send(new GetUserEnquiryByIdQuery(userId, id.Value));
            if (enquiry == null)
            {
                return NotFound();
            }

            return View(enquiry);
        }
    }
}

src/ClearSkyLettings/Controllers/HomeController.cs
using ClearSkyLettings.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace ClearSkyLettings.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/ClearSkyLettings/Controllers/PropertiesController.cs
using ClearSkyLettings.Domain.Properties.Queries;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace ClearSkyLettings.Controllers
{
    public class PropertiesController : Controller
    {
        private readonly IMediator _mediator;

        public PropertiesController(IMediator mediator)
        {
            _mediator = mediator;
        }

        // GET: Properties
        public async Task<IActionResult> Index()
        {
            var properties = await _mediator.Send(new GetAllPropertiesQuery());
            return View(properties);
        }

        // GET: Properties/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var property = await _mediator.Send(new GetPropertyByIdQuery(id.Value));
            if (property == null)
            {
                return NotFound();
            }

            return View(property);
        }

        // GET: Properties/Create
        public IActionResult Create()
        {
            return View();
        }
    }
}

src/ClearSkyLettings/Views/Enquiries/Details.cshtml
@model ClearSkyLettings.Models.Enquiry

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Enquiry</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Property)
        </dt>
        <dd class = "col-sm-10">
            <a asp-controller="Properties" asp-action="Details" asp-route-id="@Model.PropertyId">
                @Html.DisplayFor(model => model.Property.Address)
            </a>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateEnquired)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateEnquired)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to My Enquiries</a>
</div>

src/ClearSkyLettings/Views/Enquiries/Index.cshtml
@model IEnumerable<ClearSkyLettings.Models.Enquiry>

@{
    ViewData["Title"] = "My Enquiries";
}

<h1>My Enquiries</h1>

@if (Model.Count() < 1)
{
    <p>You have not made any enquiries.</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Property.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateEnquired)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Property.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateEnquired)
                    </td>
                    <td>
                        <a asp-controller="Properties" asp-action="Details" asp-route-id="@item.PropertyId">View Property</a> |
                        <a asp-controller="Enquiries" asp-action="Details" asp-route-id="@item.Id">View Enquiry</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

}

src/ClearSkyLettings/Views/Enquiries/Make.cshtml
@model ClearSkyLettings.Models.MakeEnquiryViewModel
@{
    ViewData["Title"] = "Make Enquiry";
}

<h1>Make Enquiry</h1>

<form asp-action="Make" method="post">
    <input type="hidden" class="form-control" asp-for="PropertyId" value="@Model.PropertyId" />

    <div class="form-group">
        <label for="email">Email address</label>
        <input id="email" type="email" class="form-control" asp-for="Email" placeholder="Enter your email address" />
    </div>
    
    <button type="submit" class="btn btn-primary">Enquire Now</button>
</form>

src/ClearSkyLettings/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p><a asp-controller="Properties" asp-action="Index">View properties for let</a></p>
</div>

src/ClearSkyLettings/Views/Properties/Details.cshtml
@model ClearSkyLettings.Models.Property

@{
    ViewData["Title"] = Model.Address;
}

<h1>View Property</h1>

<div>
    <h4>@Model.Address</h4>
    <hr />
    <img src="~/img/properties/@(Model.Id).jpg" class="img-fluid" alt="Image for @Model.Address" />
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MonthlyPrice)
        </dt>
        <dd class = "col-sm-10">
            £@Html.DisplayFor(model => model.MonthlyPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deposit)
        </dt>
        <dd class = "col-sm-10">
            £@Html.DisplayFor(model => model.Deposit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAdded)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsFurnished)
        </dt>
        <dd class="col-sm-10">
            @(Model.IsFurnished ? "Yes" : "No")
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberBedrooms)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberBedrooms)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberBathrooms)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberBathrooms)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PropertyType.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PropertyType.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Enquiries" asp-action="Make" asp-route-id="@Model.Id">Enquire Now</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/ClearSkyLettings/Views/Properties/Index.cshtml
@model IEnumerable<ClearSkyLettings.Models.Property>

@{
    ViewData["Title"] = "Properties";
}

<h1>Properties</h1>

@if (Model.Count() < 1)
{
    <p>Unfortunately we do not have any properties available at the moment. Please check back later.</p>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>Image</th>
                <th>
                    @Html.DisplayNameFor(model => model.Address)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MonthlyPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Deposit)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateAdded)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsFurnished)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumberBedrooms)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumberBathrooms)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PropertyType.Name)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id">
                            <img src="~/img/properties/@(item.Id).jpg" class="img-thumbnail" alt="Image for @item.Address" />
                        </a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        £@Html.DisplayFor(modelItem => item.MonthlyPrice)
                    </td>
                    <td>
                        £@Html.DisplayFor(modelItem => item.Deposit)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateAdded)
                    </td>
                    <td>
                        @(item.IsFurnished ? "Yes" : "No")
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumberBedrooms)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NumberBathrooms)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PropertyType.Name)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

}

src/ClearSkyLettings/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClearSky Lettings</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClearSky Lettings</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Properties" asp-action="Index">Properties</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Enquiries" asp-action="Index">My Enquiries</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @await Html.PartialAsync("_StatusMessages")
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ClearSky Lettings - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/ClearSkyLettings/Views/Shared/_StatusMessages.cshtml
@{
    var type = (string)TempData["_alert.type"];
    var title = (string)TempData["_alert.title"];
    var body = (string)TempData["_alert.body"];
}
@if (!string.IsNullOrEmpty(type))
{
    <div class="alert alert-@type alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>@title</strong> @body
    </div>
}